# Generated by Django 5.0.6 on 2024-05-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tournois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nbr_joueurs', models.IntegerField()),
                ('ville_assignee', models.CharField(max_length=50)),
                ('date_creation', models.IntegerField()),
            ],
        ),
    ]
