# Generated by Django 5.0.6 on 2024-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournois',
            name='date_creation',
            field=models.DateField(),
        ),
    ]
